package com.example.compareprogramming

enum class Participantypeenum {
    CONTESTANT, PRACTICE, VIRTUAL, MANAGER, OUT_OF_COMPETITION
}
enum class verdict {
    FAILED, OK , PARTIAL, COMPILATION_ERROR, RUNTIME_ERROR, WRONG_ANSWER, PRESENTATION_ERROR, TIME_LIMIT_EXCEEDED, MEMORY_LIMIT_EXCEEDED, IDLENESS_LIMIT_EXCEEDED, SECURITY_VIOLATED, CRASHED, INPUT_PREPARATION_CRASHED, CHALLENGED, SKIPPED, TESTING, REJECTED
}

enum class testset{
    SAMPLES, PRETESTS, TESTS, CHALLENGES, TESTS1, TESTS2, TESTS3,TESTS4,TESTS5,TESTS6,TESTS7, TESTS8 , TESTS9 ,TESTS10
}
enum class type{
    PROGRAMMING, QUESTION
}

enum class type_c{
    CF, IOI, ICPC
}

enum class phase {
    BEFORE, CODING, PENDING_SYSTEM_TEST, SYSTEM_TEST, FINISHED
}

